---
- name: Set up the server for Docker and docker compose installation, files setup, and application/monitoring setup
  hosts: all
  become: yes
  roles:
    - docker
    - file_setup
    - compose_setup


